[package]
name = "rust"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
actix-web = "4"
fake = "2.5.0"
diesel = { version = "1.4.4", features = ["mysql"] }
dotenv = "0.15.0"